services:
  deemix:
    container_name: deemixpessoal
    build:
      context: .
    restart: unless-stopped
    environment:
      PUID: 99
      PGID: 100
      TZ: America/Sao_Paulo
      UMASK_SET: "022"
      DISABLE_OWNERSHIP_CHECK_MUSIC: "1"
    ports:
      - "6596:6595"
    volumes:
      - type: bind
        source: /mnt/user/appdata/deemixpessoal
        target: /config
      - type: bind
        source: /mnt/remotes/media/spotify_imports
        target: /downloads
        bind:
          propagation: rslave
